export type {
	NextPage,
	NextPageContext,
	NextComponentType,
	NextApiHandler,
	NextApiRequest,
	NextApiResponse,
	GetServerSideProps,
	GetServerSidePropsContext,
	GetServerSidePropsResult,
	GetStaticPaths,
	GetStaticProps,
	GetStaticPropsContext,
	GetStaticPropsResult,
	InferGetServerSidePropsType,
	InferGetStaticPropsType,
} from 'next'
// export type {
// 	NextSeoProps,
// 	DefaultSeoProps,
// 	ArticleJsonLdProps,
// 	BreadCrumbJsonLdProps,
// 	FAQPageJsonLdProps,
// 	JobPostingJsonLdProps,
// 	BlogJsonLdProps,
// 	CourseJsonLdProps,
// 	DatasetJsonLdProps,
// 	LocalBusinessJsonLdProps,
// 	LogoJsonLdProps,
// 	ProductJsonLdProps,
// 	SocialProfileJsonLdProps,
// 	CorporateContactJsonLdProps,
// 	NewsArticleJsonLdProps,
// 	EventJsonLdProps,
// 	RecipeJsonLdProps,
// } from 'next-seo'
export type { AppProps, AppContext, NextWebVitalsMetric } from 'next/app'
