version: '3.8'

services:
  frontend-dev:
    container_name: monorepo-frontend-dev
    ports:
      - '3000:3000'
      - '9229:9229'
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./:/repo
