import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '@css/Home.module.scss'
import { VercelLogo } from '@icons'
import { cx } from '@helpers'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation, useRoutesMap } from '@hooks'

export type THomePageProps = {}

const Home: NextPage<THomePageProps> = () => {
	const { t } = useTranslation()
	const routes = useRoutesMap(t)

	return (
		<div className={styles.container}>
			<Head>
				<title>{routes.home.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					{'Welcome to '}
					<a href="https://github.com/wget-high/next-monorepo-starter#readme">
						Next.js monorepo!
					</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.tsx</code>
				</p>

				<div className={styles.grid}>
					<a
						href="https://github.com/wget-high/next-monorepo-starter#readme"
						className={cx(styles.card, styles.monorepo)}
					>
						<h2>Monorepo documentation &rarr;</h2>
						<p>Find monorepo flight manual</p>
					</a>

					<a href="https://nextjs.org/docs" className={styles.card}>
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={styles.card}
					>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						{/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
						<VercelLogo width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export const getStaticProps: GetStaticProps<THomePageProps> = async ({
	locale,
}) => {
	return {
		props: {
			...(await serverSideTranslations(String(locale), ['common'])),
		},
		revalidate: false,
	}
}

export default Home
